//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilscanExcellence.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhilscanExcellenceEntities : DbContext
    {
        public PhilscanExcellenceEntities()
            : base("name=PhilscanExcellenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExamAttachment> ExamAttachment { get; set; }
        public virtual DbSet<ExamHeader> ExamHeader { get; set; }
        public virtual DbSet<ExamItems> ExamItems { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<ResultHeader> ResultHeader { get; set; }
        public virtual DbSet<ResultItem> ResultItem { get; set; }
        public virtual DbSet<vm_RandomQuestion> vm_RandomQuestion { get; set; }
    }
}
