//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilscanExcellence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultItem
    {
        public System.Guid ID { get; set; }
        public System.Guid ResultID { get; set; }
        public System.Guid ItemID { get; set; }
        public string Answer { get; set; }
        public string AnswerDescription { get; set; }
        public int Status { get; set; }
    }
}
