//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilscanExcellence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultHeader
    {
        public System.Guid ID { get; set; }
        public System.Guid ExamID { get; set; }
        public System.Guid TakenBy { get; set; }
        public int TotalScore { get; set; }
        public int Status { get; set; }
    }
}
