//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilscanExcellence.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_RandomQuestion
    {
        public System.Guid ID { get; set; }
        public System.Guid HeaderID { get; set; }
        public string Question { get; set; }
        public string ChoiceA { get; set; }
        public string ChoiceB { get; set; }
        public string ChoiceC { get; set; }
        public string ChoiceD { get; set; }
        public string ChoiceE { get; set; }
        public string ChoiceF { get; set; }
        public string Answer { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> AttachmentID { get; set; }
        public string ShowCreatedBy { get; set; }
    }
}
